Add support for whitelisting dependencies

diff --git a/haskell-build/orb.yml b/haskell-build/orb.yml
--- a/haskell-build/orb.yml
+++ b/haskell-build/orb.yml
@@ -144,13 +144,21 @@ commands:
             cp cabal.project disable.cabal.project
             cabal new-freeze --project-file enable.cabal.project --enable-tests --enable-benchmarks
             cabal new-freeze --project-file disable.cabal.project --disable-tests --disable-benchmarks
-            (diff disable.cabal.project.freeze enable.cabal.project.freeze || true) | grep "<" | tr -s ' ' | cut -d ' ' -f 2 | cut -d '.' -f 2 > ./build/changing-dependencies.txt
-            cabal-plan info | sed -n '/^CompNameLib$/,/^$/ p' | grep '  ' | sed 's|^  ||g' | rev | cut -d '-' -f 2- | rev > ./build/immediate-dependencies.txt
-            comm -12 ./build/changing-dependencies.txt ./build/immediate-dependencies.txt > ./build/conflicting-dependencies.txt
+            (diff disable.cabal.project.freeze enable.cabal.project.freeze || true) | grep "<" | grep -v '^constraints:' | tr -s ' ' | cut -d ' ' -f 2 | cut -d '.' -f 2 > build/changing-dependencies.txt
+            cabal-plan info | sed -n '/^CompNameLib$/,/^$/ p' | grep '  ' | sed 's|^  ||g' | rev | cut -d '-' -f 2- | rev > build/immediate-dependencies.txt
+            touch .circleci/whitelist-dependencies.txt
+            comm -13 .circleci/whitelist-dependencies.txt build/immediate-dependencies.txt > build/important-dependencies.txt
+            comm -12 build/changing-dependencies.txt build/important-dependencies.txt > build/incoherent-dependencies.txt
 
-            if [ "$(cat ./build/conflicting-dependencies.txt | xargs)" != "" ]; then
-              echo "Found incoherent immediate dependencies:"
-              cat ./build/conflicting-dependencies.txt
+            echo "Changing dependencies: "
+            sed 's|^|  |g' build/changing-dependencies.txt
+            echo "Whitelisted dependencies: "
+            sed 's|^|  |g' .circleci/whitelist-dependencies.txt
+            echo "Incoherent dependencies: "
+            sed 's|^|  |g' build/incoherent-dependencies.txt
+
+            if [ "$(cat build/incoherent-dependencies.txt | xargs)" != "" ]; then
+              echo "Error: Found incoherent immediate dependencies"
               exit 1
             fi
             echo "export _BUILD_ENABLE_TESTS_FLAG=--enable-tests" >> $BASH_ENV
